// Generated by CoffeeScript 1.6.2
(function() {
  var assetsKV, env, logger, p, startAt, walk, walker, _;

  p = require("commander");

  walk = require("walk");

  logger = require("dev-logger");

  _ = require("underscore");

  env = require('./environment');

  p.version('0.1.0').option('-c, --config-file [FILE]', 'Configuration json file').parse(process.argv);

  if (p.configFile) {
    logger.info("[cdn-syncer::init] Load configuration from " + p.configFile);
    env.load(p.configFile);
  } else {
    logger.error("[cdn-syncer::init] missing configuration file, please use -c");
    process.exit(1);
  }

  assetsKV = {};

  startAt = Date.now();

  logger.log("[cdn-syncer::start] find all sgf files from " + env.LOCAL_DEPOT_ROOT);

  walker = walk.walk(env.LOCAL_DEPOT_ROOT, env.WALK_OPTIONS);

  walker.on("file", function(root, fileStats, next) {
    var fileName;

    fileName = fileStats.name;
    if (!env.REGEX_FILE_NAME) {
      assetsKV[fileName] = root;
    } else {
      if (env.REGEX_FILE_NAME.test(fileName)) {
        assetsKV[fileName] = root;
      } else {
        logger.warn("[cdn-syncer::on file] ignore invalid asset:" + fileName);
      }
    }
    next();
  });

  walker.on("errors", function(root, nodeStatsArray, next) {
    logger.error("[cdn-syncer::on error] " + arguments);
    process.exit(1);
  });

  walker.on("end", function() {
    logger.log("[cdn-syncer::list file] file " + (_.keys(assetsKV).length) + " assets, time spent:" + (Date.now() - startAt) + " ms");
    process.exit(0);
  });

}).call(this);
