// Generated by CoffeeScript 1.6.2
(function() {
  var fs, logger, settings,
    __hasProp = {}.hasOwnProperty;

  logger = require("dev-logger");

  fs = require("fs");

  settings = {
    DEBUG: true,
    LOCAL_DEPOT_ROOT: "/path/to/assets",
    WALK_OPTIONS: {
      'followLinks': false
    },
    load: function(filePath) {
      var data, key, value;

      logger.log("[environment::load] filePath:" + filePath);
      data = JSON.parse(fs.readFileSync(filePath));
      for (key in data) {
        if (!__hasProp.call(data, key)) continue;
        value = data[key];
        settings[key] = value;
      }
    }
  };

  module.exports = settings;

}).call(this);
